package trial.logisticsnetwork.response;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import java.io.Serializable;

/**
 * All responses generated by the NetworkService will be of type NetworkResponse.
 */
@XmlRootElement
public class NetworkResponse implements Serializable {

    @XmlElement
    private String message;

    public NetworkResponse() {
        this("");
    }

    public NetworkResponse(String message) {
        this.message = message;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }
}
