package trial.logisticsnetwork.response;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import java.io.Serializable;

/**
 * All responses generated by the PathService will be of type PathResponse.
 */
@XmlRootElement
public class PathResponse implements Serializable {

    @XmlElement
    private String source;

    @XmlElement
    private String target;

    @XmlElement
    private String route;

    @XmlElement
    private double distance;

    @XmlElement(name = "required-liters")
    private double requiredLiters;

    @XmlElement
    private double cost;

    @XmlElement
    private String message;

    public PathResponse() {
        this("");
    }

    public PathResponse(String message) {
        this.message = message;
    }

    public PathResponse(String source, String target, String route, double distance, double requiredLiters, double cost, String message) {
        this.source = source;
        this.target = target;
        this.route = route;
        this.distance = distance;
        this.requiredLiters = requiredLiters;
        this.cost = cost;
        this.message = message;
    }

    public String getMessage() {
        return message;
    }

    public double getDistance() {
        return distance;
    }

    public String getSource() {
        return source;
    }

    public String getTarget() {
        return target;
    }

    public String getRoute() {
        return route;
    }

    public double getRequiredLiters() {
        return requiredLiters;
    }

    public double getCost() {
        return cost;
    }
}